version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: article-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
      POSTGRES_DB: ${PG_DB:-articles}
    ports:
      - '${PG_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: article-redis
    restart: unless-stopped
    command: ['redis-server', '--save', '', '--appendonly', 'no']
    ports:
      - '${REDIS_PORT:-6379}:6379'

volumes:
  pgdata:
